groups:
  - name: chat-pdf-alerts
    rules:
      # API Health
      - alert: APIDown
        expr: up{job="chat-pdf-api"} == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Chat-PDF API is down"
          description: "The Chat-PDF API has been down for more than 30 seconds."

      # High Response Time
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High API response time"
          description: "95th percentile response time is {{ $value }} seconds."

      # High Error Rate
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.1
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "High error rate"
          description: "Error rate is {{ $value | humanizePercentage }} over the last 5 minutes."

      # Redis Down
      - alert: RedisDown
        expr: up{job="redis"} == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Redis is down"
          description: "Redis has been down for more than 30 seconds."

      # Vector DB Down
      - alert: VectorDBDown
        expr: up{job="chromadb"} == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "ChromaDB is down"
          description: "ChromaDB vector database has been down for more than 30 seconds."

      # High Memory Usage
      - alert: HighMemoryUsage
        expr: (container_memory_usage_bytes / container_spec_memory_limit_bytes) > 0.8
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage"
          description: "Container {{ $labels.name }} memory usage is {{ $value | humanizePercentage }}."

      # High CPU Usage
      - alert: HighCPUUsage
        expr: rate(container_cpu_usage_seconds_total[5m]) > 0.8
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage"
          description: "Container {{ $labels.name }} CPU usage is {{ $value | humanizePercentage }}."